### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by vnmabus** [pablomm/pablomm.github.io#1]
¡Hola Pablo!

Te escribo por aquí porque no encuentro tu email personal por ninguna parte.

Si lees este mensaje por favor mándame un correo para discutir un tema en privado, relacionado con scikit-fda.

¡Un saludo!

**Comment by pablomm** [comment]
Hola @vnmabus! Te he escrito al correo @hotmail.com que tienes en tu perfil de GitHub.
Una forma efectiva de encontrarme 😂 

Un saludo!

**Comment by pablomm** [comment]
Cierro esta issue y seguimos en contacto por mail. 
Un saludo.
